import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/src/components/ui/card';
import { Badge } from '@/src/components/ui/badge';
import { Button } from '@/src/components/ui/button';
import { 
  CheckCircle2, AlertTriangle, FileText, Download, ShieldCheck, 
  TrendingUp, ArrowRight, Layers, Building2, BrainCircuit, Users,
  BarChart3, CheckSquare, Sparkles, Filter, ChevronRight, XCircle
} from 'lucide-react';
import { ExplainabilityPanel } from './ExplainabilityPanel';

export function FinalReviewPackage() {
  const [decision, setDecision] = useState<'proceed_conditions' | 'proceed' | 'do_not_proceed'>('proceed_conditions');
  const [activeArtifactTab, setActiveArtifactTab] = useState<string>('all');

  return (
    <div className="space-y-8 animate-in fade-in duration-500 pb-16">
      {/* Header & Export Bar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-[#DEE2E6] pb-4 gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-[#005A9E] uppercase tracking-wider">Final Deliverable Package</span>
            <Badge className="bg-[#198754]">Audit Committee Ready</Badge>
          </div>
          <h2 className="text-2xl font-bold text-[#212529] mt-1">Audit Planning Package Review & Final Sign-Off</h2>
          <p className="text-xs text-[#6C757D]">Complete board-level compilation generated by AI Audit Assistant • Procure to Pay FY 2025-26</p>
        </div>

        <div className="flex items-center gap-3">
          <Button variant="outline" className="border-[#005A9E] text-[#005A9E] hover:bg-[#E5F0FA] text-xs">
            <Download className="h-3.5 w-3.5 mr-1.5" /> Export Word Package (.docx)
          </Button>
          <Button className="bg-[#005A9E] hover:bg-[#004578] text-xs">
            <Download className="h-3.5 w-3.5 mr-1.5" /> Export Complete Board PDF
          </Button>
        </div>
      </div>

      {/* FINAL AI DECISION PANEL */}
      <Card className="shadow-md border-2 border-[#005A9E] bg-white">
        <CardHeader className="p-5 border-b border-[#DEE2E6] bg-gradient-to-r from-[#F8F9FA] to-[#E5F0FA] flex flex-row items-center justify-between">
          <div className="flex items-center gap-3">
            <BrainCircuit className="h-6 w-6 text-[#005A9E]" />
            <div>
              <CardTitle className="text-base font-bold text-[#212529]">Final AI Planning Recommendation & Sign-Off</CardTitle>
              <p className="text-xs text-[#6C757D]">Automated decision engine evaluation across all 13 knowledge sources</p>
            </div>
          </div>
          <Badge variant="outline" className="border-[#198754] text-[#198754] bg-[#F0FDF4] text-xs px-3 py-1 font-bold">
            AI Overall Confidence: 94.8%
          </Badge>
        </CardHeader>
        <CardContent className="p-6 space-y-6">
          {/* Decision Buttons / Status Indicator */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div 
              onClick={() => setDecision('proceed_conditions')}
              className={`p-4 border rounded-sm cursor-pointer transition-all ${
                decision === 'proceed_conditions' 
                  ? 'border-[#FFC107] bg-[#FFF8E1] ring-2 ring-[#FFC107]' 
                  : 'border-[#DEE2E6] bg-white hover:bg-[#F8F9FA]'
              }`}
            >
              <div className="flex items-center justify-between">
                <span className="font-bold text-[#856404] text-sm">Proceed with Conditions</span>
                {decision === 'proceed_conditions' && <CheckCircle2 className="h-4 w-4 text-[#856404]" />}
              </div>
              <p className="text-xs text-[#6C757D] mt-1">Recommended. Immediate focus on Vendor Master segregation controls and Section 44AB tax filing verification.</p>
            </div>

            <div 
              onClick={() => setDecision('proceed')}
              className={`p-4 border rounded-sm cursor-pointer transition-all ${
                decision === 'proceed' 
                  ? 'border-[#198754] bg-[#F0FDF4] ring-2 ring-[#198754]' 
                  : 'border-[#DEE2E6] bg-white hover:bg-[#F8F9FA]'
              }`}
            >
              <div className="flex items-center justify-between">
                <span className="font-bold text-[#198754] text-sm">Proceed Unconditionally</span>
                {decision === 'proceed' && <CheckCircle2 className="h-4 w-4 text-[#198754]" />}
              </div>
              <p className="text-xs text-[#6C757D] mt-1">Full approval for standard audit program execution without preliminary condition restrictions.</p>
            </div>

            <div 
              onClick={() => setDecision('do_not_proceed')}
              className={`p-4 border rounded-sm cursor-pointer transition-all ${
                decision === 'do_not_proceed' 
                  ? 'border-[#A80000] bg-[#FDF2F2] ring-2 ring-[#A80000]' 
                  : 'border-[#DEE2E6] bg-white hover:bg-[#F8F9FA]'
              }`}
            >
              <div className="flex items-center justify-between">
                <span className="font-bold text-[#A80000] text-sm">Do Not Proceed</span>
                {decision === 'do_not_proceed' && <XCircle className="h-4 w-4 text-[#A80000]" />}
              </div>
              <p className="text-xs text-[#6C757D] mt-1">Halt audit until missing IT General Controls Report and updated SOP documentation are provided.</p>
            </div>
          </div>

          {/* Decision Breakdown */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-sm pt-2 border-t border-[#DEE2E6]">
            <div>
              <span className="text-[10px] font-bold text-[#6C757D] uppercase tracking-wider block mb-1">Decision Reason</span>
              <p className="text-[#212529] font-medium text-xs leading-relaxed">
                Planning readiness score reached 92%, with complete knowledge coverage across financial statements and prior reports. However, 15% override rate in vendor KYC checks mandates conditional focus during fieldwork.
              </p>
            </div>
            <div>
              <span className="text-[10px] font-bold text-[#6C757D] uppercase tracking-wider block mb-1">Key Business Impact</span>
              <p className="text-[#A80000] font-medium text-xs leading-relaxed">
                Potential financial risk exposure of $45,000 in statutory tax penalties and unmitigated risk of fictitious vendor creation in Accounts Payable ($120M throughput).
              </p>
            </div>
            <div>
              <span className="text-[10px] font-bold text-[#6C757D] uppercase tracking-wider block mb-1">Required Management Actions</span>
              <ul className="text-xs text-[#495057] space-y-1 list-disc pl-4">
                <li>Provide IT General Controls Report for ERP 3-way match.</li>
                <li>Implement dual authorization on vendor master overrides.</li>
                <li>Submit Section 44AB tax filing proof to audit team.</li>
              </ul>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* AI EXPLAINABILITY & SOURCE TRACEABILITY PANEL */}
      <ExplainabilityPanel defaultExpanded={true} />

      {/* BEFORE VS AFTER: AI IMPROVEMENT COMPARISON */}
      <Card className="shadow-sm border-[#DEE2E6]">
        <CardHeader className="p-4 border-b border-[#DEE2E6] bg-[#F8F9FA]/50">
          <CardTitle className="text-sm font-semibold flex items-center justify-between">
            <span className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#005A9E]"/> AI Value Add: Before vs After Transformation</span>
            <Badge variant="outline" className="border-[#005A9E] text-[#005A9E]">Automatic Improvement Log</Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="p-5 grid grid-cols-1 md:grid-cols-3 gap-6 text-sm">
          <div className="space-y-3">
            <h4 className="font-bold text-[#212529] border-b pb-2 flex items-center gap-2">
              <FileText className="h-4 w-4 text-[#005A9E]" /> SOP Document
            </h4>
            <div className="p-3 bg-[#F8F9FA] border border-[#DEE2E6] rounded-sm text-xs">
              <span className="text-[10px] uppercase font-bold text-[#6C757D] block">Legacy Baseline</span>
              <p className="text-[#6C757D] mt-1">Outdated 2021 manual P2P workflow without automated ERP 3-way match rules.</p>
            </div>
            <div className="p-3 bg-[#E5F0FA] border border-[#005A9E]/30 rounded-sm text-xs">
              <span className="text-[10px] uppercase font-bold text-[#005A9E] block">AI Improved Version</span>
              <p className="text-[#212529] font-medium mt-1">Full 11-clause modern SOP incorporating automated KYC steps, exception handling, and DOA limits.</p>
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="font-bold text-[#212529] border-b pb-2 flex items-center gap-2">
              <ShieldCheck className="h-4 w-4 text-[#005A9E]" /> Risk Register
            </h4>
            <div className="p-3 bg-[#F8F9FA] border border-[#DEE2E6] rounded-sm text-xs">
              <span className="text-[10px] uppercase font-bold text-[#6C757D] block">Legacy Baseline</span>
              <p className="text-[#6C757D] mt-1">Generic 5-line Excel list with missing quantitative financial impact scores.</p>
            </div>
            <div className="p-3 bg-[#E5F0FA] border border-[#005A9E]/30 rounded-sm text-xs">
              <span className="text-[10px] uppercase font-bold text-[#005A9E] block">AI Improved Version</span>
              <p className="text-[#212529] font-medium mt-1">Dynamic 8-risk matrix with evidence mapping, residual risk ratings, and automated testing procedures.</p>
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="font-bold text-[#212529] border-b pb-2 flex items-center gap-2">
              <BarChart3 className="h-4 w-4 text-[#005A9E]" /> Process Flowchart
            </h4>
            <div className="p-3 bg-[#F8F9FA] border border-[#DEE2E6] rounded-sm text-xs">
              <span className="text-[10px] uppercase font-bold text-[#6C757D] block">Legacy Baseline</span>
              <p className="text-[#6C757D] mt-1">Text-only paragraph description with zero control owner tags or decision logic points.</p>
            </div>
            <div className="p-3 bg-[#E5F0FA] border border-[#005A9E]/30 rounded-sm text-xs">
              <span className="text-[10px] uppercase font-bold text-[#005A9E] block">AI Improved Version</span>
              <p className="text-[#212529] font-medium mt-1">Structured 7-node BPMN process map marking automated controls, manual risks, and decision branches.</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* RISK TIMELINE & CONTROL EFFECTIVENESS */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Risk Trend Timeline */}
        <Card className="shadow-sm border-[#DEE2E6]">
          <CardHeader className="p-4 border-b border-[#DEE2E6] bg-[#F8F9FA]/50">
            <CardTitle className="text-sm font-semibold flex items-center justify-between">
              <span className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-[#005A9E]"/> Multi-Year Risk Rating Trend</span>
              <Badge variant="outline" className="text-[10px]">FY22 - FY26</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-5 space-y-4 text-xs">
            <div className="grid grid-cols-5 gap-2 text-center">
              <div className="p-2.5 bg-[#F8F9FA] border rounded-sm">
                <span className="font-bold text-[#6C757D] block">FY22</span>
                <Badge className="mt-1 bg-[#198754]">Low</Badge>
                <span className="text-[9px] text-[#6C757D] block mt-1">2 Findings</span>
              </div>
              <div className="p-2.5 bg-[#F8F9FA] border rounded-sm">
                <span className="font-bold text-[#6C757D] block">FY23</span>
                <Badge className="mt-1 bg-[#198754]">Low</Badge>
                <span className="text-[9px] text-[#6C757D] block mt-1">3 Findings</span>
              </div>
              <div className="p-2.5 bg-[#FFF3CD] border border-[#FFC107] rounded-sm">
                <span className="font-bold text-[#856404] block">FY24</span>
                <Badge className="mt-1 bg-[#FFC107] text-[#856404]">Medium</Badge>
                <span className="text-[9px] text-[#856404] block mt-1">5 Findings</span>
              </div>
              <div className="p-2.5 bg-[#FDF2F2] border border-[#A80000] rounded-sm">
                <span className="font-bold text-[#A80000] block">FY25</span>
                <Badge className="mt-1 bg-[#A80000]">High</Badge>
                <span className="text-[9px] text-[#A80000] block mt-1">8 Findings</span>
              </div>
              <div className="p-2.5 bg-[#E5F0FA] border border-[#005A9E] rounded-sm">
                <span className="font-bold text-[#005A9E] block">FY26 (Current)</span>
                <Badge className="mt-1 bg-[#A80000]">High</Badge>
                <span className="text-[9px] text-[#005A9E] block mt-1">Targeted Audit</span>
              </div>
            </div>
            <p className="text-[#6C757D] italic border-t pt-2">
              <strong>Risk Trajectory:</strong> Risk score increased sharply following FY25 ERP system migration due to unmitigated manual override permissions.
            </p>
          </CardContent>
        </Card>

        {/* Control Effectiveness & Coverage */}
        <Card className="shadow-sm border-[#DEE2E6]">
          <CardHeader className="p-4 border-b border-[#DEE2E6] bg-[#F8F9FA]/50">
            <CardTitle className="text-sm font-semibold flex items-center justify-between">
              <span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#198754]"/> Control Coverage & Effectiveness</span>
              <Badge className="bg-[#198754]">82% Coverage</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-5 space-y-4 text-xs">
            <div className="grid grid-cols-4 gap-3 text-center">
              <div className="p-2.5 bg-white border border-[#DEE2E6] rounded-sm">
                <span className="text-[10px] text-[#6C757D] block uppercase font-bold">Total Controls</span>
                <span className="text-lg font-bold text-[#212529]">12</span>
              </div>
              <div className="p-2.5 bg-[#F0FDF4] border border-[#198754]/30 rounded-sm">
                <span className="text-[10px] text-[#198754] block uppercase font-bold">Effective</span>
                <span className="text-lg font-bold text-[#198754]">8</span>
              </div>
              <div className="p-2.5 bg-[#FFF3CD] border border-[#FFC107]/30 rounded-sm">
                <span className="text-[10px] text-[#856404] block uppercase font-bold">Needs Imp.</span>
                <span className="text-lg font-bold text-[#856404]">3</span>
              </div>
              <div className="p-2.5 bg-[#FDF2F2] border border-[#A80000]/30 rounded-sm">
                <span className="text-[10px] text-[#A80000] block uppercase font-bold">Missing</span>
                <span className="text-lg font-bold text-[#A80000]">1</span>
              </div>
            </div>

            <div className="space-y-2">
              <div className="flex justify-between text-xs text-[#212529]">
                <span>Automated Controls Ratio:</span>
                <span className="font-bold">66% (8 of 12 controls)</span>
              </div>
              <div className="w-full bg-[#E9ECEF] h-2 rounded-full overflow-hidden">
                <div className="bg-[#005A9E] h-2 rounded-full w-[66%]"></div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* MANAGEMENT ACTION PLAN (Action Timeline) */}
      <Card className="shadow-sm border-[#DEE2E6]">
        <CardHeader className="p-4 border-b border-[#DEE2E6] bg-[#F8F9FA]/50">
          <CardTitle className="text-sm font-semibold flex items-center gap-2">
            <CheckSquare className="h-4 w-4 text-[#005A9E]" /> Structured Management Action Plan
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <table className="w-full text-sm text-left border-collapse">
            <thead className="bg-[#F8F9FA] text-[#6C757D] text-[11px] uppercase tracking-wider border-b border-[#DEE2E6]">
              <tr>
                <th className="px-4 py-3 font-semibold w-28">Timeframe</th>
                <th className="px-4 py-3 font-semibold">Action Required</th>
                <th className="px-4 py-3 font-semibold">Owner</th>
                <th className="px-4 py-3 font-semibold">Expected Business Benefit</th>
                <th className="px-4 py-3 font-semibold text-right">Priority</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#DEE2E6] text-xs text-[#495057]">
              <tr className="hover:bg-[#F8F9FA]">
                <td className="px-4 py-3.5 font-bold text-[#A80000]">Immediate (7 Days)</td>
                <td className="px-4 py-3.5 font-medium text-[#212529]">Implement mandatory dual authorization on all Vendor Master KYC overrides.</td>
                <td className="px-4 py-3.5">CPO & AP Manager</td>
                <td className="px-4 py-3.5 text-[#198754]">Prevents fictitious vendor creation</td>
                <td className="px-4 py-3.5 text-right"><Badge className="bg-[#A80000]">High</Badge></td>
              </tr>
              <tr className="hover:bg-[#F8F9FA]">
                <td className="px-4 py-3.5 font-bold text-[#005A9E]">Short Term (30 Days)</td>
                <td className="px-4 py-3.5 font-medium text-[#212529]">Submit overdue statutory returns under Section 44AB and reconcile tax notices.</td>
                <td className="px-4 py-3.5">Tax & Finance Lead</td>
                <td className="px-4 py-3.5 text-[#198754]">Eliminates $45,000 regulatory penalties</td>
                <td className="px-4 py-3.5 text-right"><Badge className="bg-[#005A9E]">Medium</Badge></td>
              </tr>
              <tr className="hover:bg-[#F8F9FA]">
                <td className="px-4 py-3.5 font-bold text-[#6C757D]">Long Term (60 Days)</td>
                <td className="px-4 py-3.5 font-medium text-[#212529]">Update baseline Operating SOP document to mirror post-ERP automated controls.</td>
                <td className="px-4 py-3.5">Process Owner</td>
                <td className="px-4 py-3.5 text-[#198754]">Ensures long-term operational compliance</td>
                <td className="px-4 py-3.5 text-right"><Badge variant="outline" className="border-[#6C757D] text-[#6C757D]">Low</Badge></td>
              </tr>
            </tbody>
          </table>
        </CardContent>
      </Card>

      {/* ALL 10 PACKAGE ARTIFACTS SUMMARY LIST */}
      <Card className="shadow-sm border-[#DEE2E6]">
        <CardHeader className="p-4 border-b border-[#DEE2E6] bg-[#F8F9FA]/50 flex flex-row items-center justify-between">
          <CardTitle className="text-sm font-semibold flex items-center gap-2">
            <Layers className="h-4 w-4 text-[#005A9E]" /> Complete Audit Planning Package Deliverables
          </CardTitle>
          <span className="text-xs text-[#6C757D]">10 of 10 Artifacts Generated</span>
        </CardHeader>
        <CardContent className="p-0">
          <div className="grid grid-cols-1 md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-[#DEE2E6]">
            {/* Left Column */}
            <div className="divide-y divide-[#DEE2E6]">
              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">1. Board Executive Summary</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>

              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">2. Business Understanding Document</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>

              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">3. Generated Standard Operating Procedure (SOP)</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>

              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">4. Business Process Flowchart (BPMN)</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>

              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">5. Historical Trend Analysis (5 Years)</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>
            </div>

            {/* Right Column */}
            <div className="divide-y divide-[#DEE2E6]">
              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">6. Financial Analysis & Materiality</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>

              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">7. AI Risk Register</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>

              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">8. Audit Planning Memorandum</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>

              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">9. Audit Scoping Document</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>

              <div className="p-3.5 flex items-center justify-between hover:bg-[#F8F9FA]">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 text-[#198754]" />
                  <span className="text-xs font-semibold text-[#212529]">10. Detailed Substantive Audit Program</span>
                </div>
                <Badge variant="outline" className="text-[10px] border-[#198754] text-[#198754]">Ready</Badge>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
